name: Deploy Infrastructure

on:
  push:
    branches:
      - dev 
    paths:
      - infra/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: pulumi stack select muazhussain/k3s-deployment-automation/dev --cwd infra

      - name: Set public key environment variable
        run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Pulumi refresh
        run: pulumi refresh --yes --cwd infra

      - name: Pulumi up
        run: pulumi up --yes --cwd infra

      - name: Save pulumi outputs
        id: pulumi_outputs
        run: |
          GIT_RUNNER_PUBLIC_IP=$(pulumi stack output git_runner_public_ip --cwd infra)
          MASTER_PRIVATE_IP=$(pulumi stack output master_private_ip --cwd infra)
          WORKER_1_PRIVATE_IP=$(pulumi stack output worker_1_private_ip --cwd infra)
          WORKER_2_PRIVATE_IP=$(pulumi stack output worker_2_private_ip --cwd infra)

          echo "GIT_RUNNER_IP=${GIT_RUNNER_PUBLIC_IP}" >> $GITHUB_ENV
          echo "MASTER_IP=${MASTER_PRIVATE_IP}" >> $GITHUB_ENV
          echo "WORKER_1_IP=${WORKER_1_PRIVATE_IP}" >> $GITHUB_ENV
          echo "WORKER_2_IP=${WORKER_2_PRIVATE_IP}" >> $GITHUB_ENV
