name: Setup Github Runner and Ansible

on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Select Pulumi stack
        run: pulumi stack select muazhussain/k3s-deployment-automation/dev --cwd infra

      - name: Refresh Pulumi stack
        run: pulumi refresh --yes --cwd infra

      - name: Save Pulumi outputs to GitHub environment
        id: pulumi_outputs
        run: |
          GIT_RUNNER_PUBLIC_IP=$(pulumi stack output git_runner_public_ip --cwd infra)
          MASTER_PRIVATE_IP=$(pulumi stack output master_private_ip --cwd infra)
          WORKER_1_PRIVATE_IP=$(pulumi stack output worker_1_private_ip --cwd infra)
          WORKER_2_PRIVATE_IP=$(pulumi stack output worker_2_private_ip --cwd infra)
          echo "GIT_RUNNER_IP=${GIT_RUNNER_PUBLIC_IP}" >> $GITHUB_ENV
          echo "MASTER_IP=${MASTER_PRIVATE_IP}" >> $GITHUB_ENV
          echo "WORKER_1_IP=${WORKER_1_PRIVATE_IP}" >> $GITHUB_ENV
          echo "WORKER_2_IP=${WORKER_2_PRIVATE_IP}" >> $GITHUB_ENV
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Runner EC2 to install GitHub Runner and Ansible
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.GIT_RUNNER_IP }} << EOF
          sudo apt-get update -y
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ansible --version

          mkdir actions-runner && cd actions-runner

          curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz

          echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c

          tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz

          ./config.sh --url https://github.com/Konami33/k3s-deployment --token AQGGSGXEHNCEG7HR5YI4D4LGQXPVG --name "Git Runner 2"

          sudo ./svc.sh install
          sudo ./svc.sh start
          EOF

      - name: Copy Ansible directory to GitHub Runner
        run: |
          scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/ansible ubuntu@${{ env.GIT_RUNNER_IP }}:/home/ubuntu/

      - name: SSH into GitHub Runner and run Ansible playbook
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.GIT_RUNNER_IP }} << 'EOF'

          # Create inventory file with dynamic IPs
          cat <<EOT > /home/ubuntu/ansible/inventory/hosts.ini
          [master]
          master-node ansible_host=${{ env.MASTER_IP }}

          [workers]
          worker-node-1 ansible_host=${{ env.WORKER_1_IP }}
          worker-node-2 ansible_host=${{ env.WORKER_2_IP }}

          [k3s_cluster:children]
          master
          workers
          EOT
          EOF
